name: Heartbeat
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - pip:
      - torch==2.5.1
      - wfdb==4.1.2
      - scikit-learn==1.6.1
      - omegaconf==2.3.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - seaborn==0.13.2
      - biosppy==2.2.2
